import type { WorkoutSession } from './types'

const ABS = [
  'Cable Crunch - 3 sets x 15 reps, RPE 7, rest 60s',
  'Hanging Leg Raise - 3 sets x 12 reps, RPE 7, rest 60s',
  'Pallof Press - 3 sets x 12 reps each side, RPE 7, rest 45s',
  'Dragon Flag Progression - 3 sets x 6 reps, RPE 8, rest 90s',
  'Plank - 3 sets x 60 seconds, RPE 7, rest 45s',
  'Russian Twist - 3 sets x 20 reps, RPE 7, rest 45s',
  'Cable Crunch - 3 sets x 20 reps, RPE 7, rest 45s',
  'Hanging Leg Raise - 3 sets x 15 reps, RPE 7, rest 45s',
  'Pallof Press - 3 sets x 15 reps each side, RPE 7, rest 45s',
  'Plank - 3 sets x 45 seconds, RPE 7, rest 30s',
] as const

const BICEPS = [
  'Barbell Curl - 3 sets x 12 reps, RPE 7, rest 60s',
  'Dumbbell Hammer Curl - 3 sets x 12 reps, RPE 7, rest 60s',
  'Incline Dumbbell Curl - 3 sets x 12 reps, RPE 7, rest 60s',
  'Concentration Curl - 3 sets x 12 reps each side, RPE 7, rest 60s',
  'Cable Rope Hammer Curl - 3 sets x 15 reps, RPE 7, rest 45s',
  'EZ Bar Preacher Curl - 3 sets x 12 reps, RPE 7, rest 60s',
  'Reverse Cable Curl - 3 sets x 15 reps, RPE 7, rest 45s',
  'Dumbbell Concentration Curl - 3 sets x 12 reps each side, RPE 7, rest 60s',
  'EZ Bar Curl - 3 sets x 12 reps, RPE 7, rest 60s',
  'Machine Preacher Curl - 3 sets x 12 reps, RPE 7, rest 60s',
] as const

const TRICEPS = [
  'Rope Triceps Pushdown - 3 sets x 12 reps, RPE 7, rest 60s',
  'Overhead Cable Triceps Extension - 3 sets x 12 reps, RPE 7, rest 60s',
  'Skull Crusher - 3 sets x 12 reps, RPE 7, rest 60s',
  'Dip Machine - 3 sets x 12 reps, RPE 7, rest 75s',
  'Reverse Grip Cable Pushdown - 3 sets x 15 reps, RPE 7, rest 45s',
  'Close Grip Bench Press - 3 sets x 10 reps, RPE 7, rest 90s',
  'Overhead Dumbbell Extension - 3 sets x 12 reps, RPE 7, rest 60s',
  'Cable Triceps Kickback - 3 sets x 15 reps, RPE 7, rest 45s',
  'Triceps Dips - 3 sets x AMRAP, RPE 7, rest 60s',
  'Push-up - 3 sets x AMRAP, RPE 7, rest 45s',
] as const

export const workoutSessions: WorkoutSession[] = [
  // ===== PUSH VARIATIONS (10) — each ends with one abs exercise =====
  {
    id: 'push-01',
    type: 'push',
    title: 'Heavy Bench & Overhead',
    workout: [
      'Barbell Bench Press - 5 sets x 5 reps, RPE 8, rest 180s',
      'Standing Overhead Press - 4 sets x 6 reps, RPE 8, rest 150s',
      'Incline Dumbbell Press - 3 sets x 10 reps, RPE 7, rest 90s',
      'Dumbbell Lateral Raise - 3 sets x 12 reps, RPE 7, rest 60s',
      'Rope Triceps Pushdown - 3 sets x 12 reps, RPE 7, rest 60s',      BICEPS[8],      BICEPS[0],
      ABS[0],
    ],
  },
  {
    id: 'push-02',
    type: 'push',
    title: 'Hypertrophy Chest & Triceps',
    workout: [
      'Dumbbell Bench Press - 4 sets x 12 reps, RPE 7, rest 75s',
      'Incline Dumbbell Press - 4 sets x 10 reps, RPE 7, rest 90s',
      'Cable Crossover - 3 sets x 15 reps, RPE 7, rest 60s',
      'Overhead Cable Triceps Extension - 4 sets x 12 reps, RPE 7, rest 60s',
      'Skull Crusher - 3 sets x 12 reps, RPE 7, rest 60s',
      'Dumbbell Lateral Raise - 3 sets x 15 reps, RPE 7, rest 45s',
      BICEPS[1],
      ABS[1],
    ],
  },
  {
    id: 'push-03',
    type: 'push',
    title: 'Shoulder Dominant Push',
    workout: [
      'Standing Overhead Press - 5 sets x 5 reps, RPE 8, rest 180s',
      'Dumbbell Shoulder Press - 4 sets x 10 reps, RPE 7, rest 90s',
      'Cable Lateral Raise - 4 sets x 15 reps, RPE 7, rest 60s',
      'Reverse Pec Deck - 4 sets x 15 reps, RPE 7, rest 60s',
      'Face Pulls - 3 sets x 20 reps, RPE 7, rest 45s',
      'Dip Machine - 3 sets x 12 reps, RPE 7, rest 75s',
      BICEPS[2],
      ABS[2],
    ],
  },
  {
    id: 'push-04',
    type: 'push',
    title: 'Chest Specialization',
    workout: [
      'Barbell Bench Press - 4 sets x 8 reps, RPE 8, rest 120s',
      'Incline Dumbbell Press - 4 sets x 10 reps, RPE 7, rest 90s',
      'Machine Chest Press - 3 sets x 12 reps, RPE 7, rest 75s',
      'Cable Crossover - 3 sets x 15 reps, RPE 7, rest 60s',
      'Dumbbell Bench Press - 3 sets x 12 reps, RPE 7, rest 75s',
      'Push-up - 3 sets x AMRAP, RPE 7, rest 45s',
      BICEPS[3],
      ABS[3],
    ],
  },
  {
    id: 'push-05',
    type: 'push',
    title: 'Triceps Annihilation',
    workout: [
      'Close Grip Bench Press - 4 sets x 8 reps, RPE 8, rest 90s',
      'Dip Machine - 4 sets x 10 reps, RPE 7, rest 75s',
      'Skull Crusher - 4 sets x 12 reps, RPE 7, rest 60s',
      'Overhead Cable Triceps Extension - 3 sets x 15 reps, RPE 7, rest 45s',
      'Rope Triceps Pushdown - 3 sets x 15 reps, RPE 7, rest 45s',
      'Reverse Grip Cable Pushdown - 3 sets x 20 reps, RPE 7, rest 30s',
      ABS[4],
    ],
  },
  {
    id: 'push-06',
    type: 'push',
    title: 'Power Push Day',
    workout: [
      'Barbell Bench Press - 3 sets x 3 reps, RPE 9, rest 180s',
      'Standing Overhead Press - 3 sets x 5 reps, RPE 8, rest 150s',
      'Incline Dumbbell Press - 3 sets x 8 reps, RPE 7, rest 90s',
      'Dumbbell Lateral Raise - 3 sets x 12 reps, RPE 7, rest 60s',
      'Rope Triceps Pushdown - 3 sets x 10 reps, RPE 7, rest 60s',      BICEPS[4],      ABS[5],
    ],
  },
  {
    id: 'push-07',
    type: 'push',
    title: 'Upper Chest Focus',
    workout: [
      'Incline Dumbbell Press - 5 sets x 8 reps, RPE 8, rest 90s',
      'Barbell Incline Bench Press - 4 sets x 10 reps, RPE 7, rest 90s',
      'Cable Incline Fly - 3 sets x 12 reps, RPE 7, rest 75s',
      'Standing Overhead Press - 3 sets x 10 reps, RPE 7, rest 90s',
      'Dumbbell Lateral Raise - 3 sets x 15 reps, RPE 7, rest 45s',
      'Overhead Cable Triceps Extension - 3 sets x 12 reps, RPE 7, rest 60s',      BICEPS[5],      ABS[6],
    ],
  },
  {
    id: 'push-08',
    type: 'push',
    title: 'Dumbbell-Only Push',
    workout: [
      'Dumbbell Bench Press - 4 sets x 10 reps, RPE 7, rest 90s',
      'Dumbbell Shoulder Press - 4 sets x 10 reps, RPE 7, rest 90s',
      'Incline Dumbbell Press - 3 sets x 12 reps, RPE 7, rest 75s',
      'Dumbbell Lateral Raise - 3 sets x 15 reps, RPE 7, rest 60s',
      'Overhead Dumbbell Extension - 3 sets x 12 reps, RPE 7, rest 60s',
      'Dumbbell Front Raise - 3 sets x 15 reps, RPE 7, rest 45s',      BICEPS[6],      ABS[7],
    ],
  },
  {
    id: 'push-09',
    type: 'push',
    title: 'High Volume Push',
    workout: [
      'Barbell Bench Press - 4 sets x 10 reps, RPE 7, rest 90s',
      'Seated Dumbbell Press - 4 sets x 12 reps, RPE 7, rest 75s',
      'Cable Crossover - 4 sets x 15 reps, RPE 7, rest 60s',
      'Dumbbell Lateral Raise - 4 sets x 15 reps, RPE 7, rest 45s',
      'Rope Triceps Pushdown - 4 sets x 15 reps, RPE 7, rest 45s',
      'Skull Crusher - 3 sets x 12 reps, RPE 7, rest 60s',
      'Face Pulls - 3 sets x 20 reps, RPE 7, rest 30s',      BICEPS[7],      ABS[8],
    ],
  },
  {
    id: 'push-10',
    type: 'push',
    title: 'Machine Push Day',
    workout: [
      'Machine Chest Press - 4 sets x 10 reps, RPE 7, rest 90s',
      'Machine Shoulder Press - 4 sets x 12 reps, RPE 7, rest 75s',
      'Cable Crossover - 3 sets x 15 reps, RPE 7, rest 60s',
      'Cable Lateral Raise - 3 sets x 15 reps, RPE 7, rest 60s',
      'Dip Machine - 3 sets x 12 reps, RPE 7, rest 75s',
      'Rope Triceps Pushdown - 3 sets x 15 reps, RPE 7, rest 45s',
      BICEPS[9],
      ABS[9],
    ],
  },

  // ===== PULL VARIATIONS (10) — each ends with one abs exercise =====
  {
    id: 'pull-01',
    type: 'pull',
    title: 'Heavy Deadlift & Rows',
    workout: [
      'Deadlift - 5 sets x 5 reps, RPE 8, rest 180s',
      'Weighted Pull-up - 4 sets x 6 reps, RPE 8, rest 120s',
      'Barbell Pendlay Row - 4 sets x 8 reps, RPE 7, rest 90s',
      'Barbell Curl - 3 sets x 10 reps, RPE 7, rest 60s',
      'Face Pulls - 3 sets x 15 reps, RPE 7, rest 60s',
      TRICEPS[0],
      ABS[1],
    ],
  },
  {
    id: 'pull-02',
    type: 'pull',
    title: 'Hypertrophy Back & Biceps',
    workout: [
      'Lat Pulldown - 4 sets x 12 reps, RPE 7, rest 75s',
      'Seated Cable Row - 4 sets x 12 reps, RPE 7, rest 75s',
      'Dumbbell Hammer Curl - 3 sets x 12 reps, RPE 7, rest 60s',
      'Incline Dumbbell Curl - 3 sets x 12 reps, RPE 7, rest 60s',
      'Barbell Shrug - 4 sets x 15 reps, RPE 7, rest 60s',
      'Face Pulls - 3 sets x 20 reps, RPE 7, rest 45s',
      TRICEPS[1],
      ABS[0],
    ],
  },
  {
    id: 'pull-03',
    type: 'pull',
    title: 'Vertical Pull Focus',
    workout: [
      'Weighted Pull-up - 5 sets x 8 reps, RPE 8, rest 120s',
      'Lat Pulldown - 4 sets x 12 reps, RPE 7, rest 75s',
      'Assisted Chin-up Machine - 3 sets x 10 reps, RPE 7, rest 90s',
      'Barbell Curl - 4 sets x 10 reps, RPE 7, rest 60s',
      'Dumbbell Hammer Curl - 3 sets x 12 reps, RPE 7, rest 60s',
      TRICEPS[2],
      ABS[2],
    ],
  },
  {
    id: 'pull-04',
    type: 'pull',
    title: 'Horizontal Pull Focus',
    workout: [
      'Barbell Pendlay Row - 5 sets x 8 reps, RPE 8, rest 90s',
      'Seated Cable Row - 4 sets x 12 reps, RPE 7, rest 75s',
      'Sealed Chest Supported Row - 3 sets x 12 reps, RPE 7, rest 75s',
      'Dumbbell Row - 3 sets x 10 reps each side, RPE 7, rest 90s',
      'Barbell Curl - 3 sets x 12 reps, RPE 7, rest 60s',
      'Face Pulls - 3 sets x 15 reps, RPE 7, rest 45s',
      TRICEPS[3],
      ABS[3],
    ],
  },
  {
    id: 'pull-05',
    type: 'pull',
    title: 'Biceps Specialization',
    workout: [
      'Lat Pulldown - 4 sets x 10 reps, RPE 7, rest 90s',
      'Seated Cable Row - 3 sets x 12 reps, RPE 7, rest 75s',
      'Barbell Curl - 4 sets x 10 reps, RPE 8, rest 75s',
      'Incline Dumbbell Curl - 4 sets x 12 reps, RPE 7, rest 60s',
      'Concentration Curl - 3 sets x 12 reps each side, RPE 7, rest 60s',
      'Cable Rope Hammer Curl - 3 sets x 15 reps, RPE 7, rest 45s',
      TRICEPS[4],
      ABS[4],
    ],
  },
  {
    id: 'pull-06',
    type: 'pull',
    title: 'Posterior Chain Pull',
    workout: [
      'Deadlift - 4 sets x 5 reps, RPE 8, rest 180s',
      'Romanian Deadlift - 4 sets x 10 reps, RPE 7, rest 90s',
      'Barbell Pendlay Row - 3 sets x 10 reps, RPE 7, rest 90s',
      'Barbell Shrug - 4 sets x 12 reps, RPE 7, rest 60s',
      'Barbell Curl - 3 sets x 10 reps, RPE 7, rest 60s',
      TRICEPS[5],
      ABS[5],
    ],
  },
  {
    id: 'pull-07',
    type: 'pull',
    title: 'Power Pull Day',
    workout: [
      'Deadlift - 3 sets x 3 reps, RPE 9, rest 180s',
      'Weighted Pull-up - 3 sets x 5 reps, RPE 8, rest 150s',
      'Barbell Pendlay Row - 3 sets x 5 reps, RPE 8, rest 120s',
      'Barbell Curl - 3 sets x 8 reps, RPE 7, rest 60s',
      TRICEPS[6],
      ABS[6],
    ],
  },
  {
    id: 'pull-08',
    type: 'pull',
    title: 'Dumbbell-Only Pull',
    workout: [
      'Dumbbell Row - 4 sets x 10 reps each side, RPE 7, rest 90s',
      'Dumbbell Romanian Deadlift - 4 sets x 12 reps, RPE 7, rest 90s',
      'Dumbbell Hammer Curl - 4 sets x 12 reps, RPE 7, rest 60s',
      'Dumbbell Concentration Curl - 3 sets x 12 reps each side, RPE 7, rest 60s',
      'Dumbbell Shrug - 4 sets x 12 reps, RPE 7, rest 60s',
      'Dumbbell Reverse Fly - 3 sets x 15 reps, RPE 7, rest 45s',
      TRICEPS[7],
      ABS[7],
    ],
  },
  {
    id: 'pull-09',
    type: 'pull',
    title: 'High Volume Pull',
    workout: [
      'Lat Pulldown - 5 sets x 12 reps, RPE 7, rest 75s',
      'Seated Cable Row - 5 sets x 12 reps, RPE 7, rest 75s',
      'Assisted Chin-up Machine - 3 sets x 10 reps, RPE 7, rest 90s',
      'Reverse Pec Deck - 4 sets x 15 reps, RPE 7, rest 45s',
      'Barbell Curl - 4 sets x 12 reps, RPE 7, rest 60s',
      'Incline Dumbbell Curl - 3 sets x 15 reps, RPE 7, rest 45s',
      'Face Pulls - 3 sets x 20 reps, RPE 7, rest 30s',
      TRICEPS[8],
      ABS[8],
    ],
  },
  {
    id: 'pull-10',
    type: 'pull',
    title: 'Machine Pull Day',
    workout: [
      'Lat Pulldown - 4 sets x 10 reps, RPE 7, rest 90s',
      'Machine Row - 4 sets x 12 reps, RPE 7, rest 75s',
      'Machine Curl - 4 sets x 12 reps, RPE 7, rest 60s',
      'Reverse Cable Curl - 3 sets x 15 reps, RPE 7, rest 45s',
      'Barbell Shrug - 4 sets x 12 reps, RPE 7, rest 60s',
      TRICEPS[9],
      ABS[9],
    ],
  },

  // ===== LEGS VARIATIONS (10) — each has core finisher =====
  {
    id: 'legs-01',
    type: 'legs',
    title: 'Heavy Squat Day',
    workout: [
      'Barbell Back Squat - 5 sets x 5 reps, RPE 8, rest 180s',
      'Romanian Deadlift - 4 sets x 8 reps, RPE 7, rest 120s',
      'Leg Press - 3 sets x 12 reps, RPE 7, rest 90s',
      'Standing Calf Raise - 4 sets x 15 reps, RPE 7, rest 60s',
      'Cable Crunch - 3 sets x 15 reps, RPE 7, rest 60s',
    ],
  },
  {
    id: 'legs-02',
    type: 'legs',
    title: 'Hypertrophy Legs',
    workout: [
      'Leg Press - 4 sets x 12 reps, RPE 7, rest 90s',
      'Walking Lunge - 3 sets x 12 reps each leg, RPE 7, rest 90s',
      'Romanian Deadlift - 4 sets x 12 reps, RPE 7, rest 90s',
      'Leg Extension - 3 sets x 15 reps, RPE 7, rest 60s',
      'Leg Curl - 3 sets x 15 reps, RPE 7, rest 60s',
      'Seated Calf Raise - 4 sets x 20 reps, RPE 7, rest 45s',
      'Plank - 3 sets x 60 seconds, RPE 7, rest 45s',
    ],
  },
  {
    id: 'legs-03',
    type: 'legs',
    title: 'Quad Focus',
    workout: [
      'Barbell Back Squat - 4 sets x 10 reps, RPE 8, rest 120s',
      'Front Squat - 3 sets x 8 reps, RPE 7, rest 120s',
      'Leg Extension - 4 sets x 15 reps, RPE 7, rest 60s',
      'Walking Lunge - 3 sets x 12 reps each leg, RPE 7, rest 90s',
      'Standing Calf Raise - 4 sets x 15 reps, RPE 7, rest 60s',
      'Hanging Leg Raise - 3 sets x 12 reps, RPE 7, rest 60s',
    ],
  },
  {
    id: 'legs-04',
    type: 'legs',
    title: 'Hamstring & Glute Focus',
    workout: [
      'Romanian Deadlift - 5 sets x 10 reps, RPE 8, rest 90s',
      'Glute Bridge - 4 sets x 15 reps, RPE 7, rest 60s',
      'Leg Curl - 4 sets x 15 reps, RPE 7, rest 60s',
      'Bulgarian Split Squat - 3 sets x 10 reps each leg, RPE 7, rest 90s',
      'Seated Calf Raise - 4 sets x 15 reps, RPE 7, rest 60s',
      'Pallof Press - 3 sets x 12 reps each side, RPE 7, rest 45s',
    ],
  },
  {
    id: 'legs-05',
    type: 'legs',
    title: 'Calf & Core Emphasis',
    workout: [
      'Barbell Back Squat - 4 sets x 8 reps, RPE 8, rest 120s',
      'Leg Press - 4 sets x 12 reps, RPE 7, rest 90s',
      'Standing Calf Raise - 5 sets x 15 reps, RPE 8, rest 45s',
      'Seated Calf Raise - 5 sets x 20 reps, RPE 7, rest 30s',
      'Hanging Leg Raise - 4 sets x 15 reps, RPE 7, rest 60s',
      'Cable Crunch - 4 sets x 20 reps, RPE 7, rest 45s',
      'Pallof Press - 3 sets x 12 reps each side, RPE 7, rest 45s',
    ],
  },
  {
    id: 'legs-06',
    type: 'legs',
    title: 'Power Leg Day',
    workout: [
      'Barbell Back Squat - 3 sets x 3 reps, RPE 9, rest 180s',
      'Deadlift - 3 sets x 3 reps, RPE 9, rest 180s',
      'Leg Press - 3 sets x 6 reps, RPE 8, rest 120s',
      'Standing Calf Raise - 3 sets x 8 reps, RPE 8, rest 60s',
      'Plank - 3 sets x 60 seconds, RPE 7, rest 45s',
    ],
  },
  {
    id: 'legs-07',
    type: 'legs',
    title: 'Unilateral Leg Day',
    workout: [
      'Bulgarian Split Squat - 4 sets x 10 reps each leg, RPE 8, rest 90s',
      'Walking Lunge - 3 sets x 12 reps each leg, RPE 7, rest 90s',
      'Single-Leg RDL - 3 sets x 10 reps each leg, RPE 7, rest 90s',
      'Leg Extension - 3 sets x 15 reps, RPE 7, rest 60s',
      'Leg Curl - 3 sets x 15 reps, RPE 7, rest 60s',
      'Standing Calf Raise - 4 sets x 15 reps, RPE 7, rest 60s',
      'Russian Twist - 3 sets x 20 reps, RPE 7, rest 45s',
    ],
  },
  {
    id: 'legs-08',
    type: 'legs',
    title: 'Dumbbell-Only Legs',
    workout: [
      'Dumbbell Goblet Squat - 4 sets x 12 reps, RPE 7, rest 90s',
      'Dumbbell Walking Lunge - 3 sets x 12 reps each leg, RPE 7, rest 90s',
      'Dumbbell Romanian Deadlift - 4 sets x 12 reps, RPE 7, rest 90s',
      'Dumbbell Step-up - 3 sets x 10 reps each leg, RPE 7, rest 90s',
      'Dumbbell Calf Raise - 4 sets x 15 reps, RPE 7, rest 60s',
      'Plank - 3 sets x 45 seconds, RPE 7, rest 45s',
    ],
  },
  {
    id: 'legs-09',
    type: 'legs',
    title: 'High Volume Legs',
    workout: [
      'Barbell Back Squat - 5 sets x 10 reps, RPE 7, rest 120s',
      'Romanian Deadlift - 4 sets x 12 reps, RPE 7, rest 90s',
      'Leg Press - 4 sets x 15 reps, RPE 7, rest 75s',
      'Leg Extension - 4 sets x 15 reps, RPE 7, rest 60s',
      'Leg Curl - 4 sets x 15 reps, RPE 7, rest 60s',
      'Standing Calf Raise - 5 sets x 20 reps, RPE 7, rest 45s',
      'Cable Crunch - 3 sets x 15 reps, RPE 7, rest 60s',
    ],
  },
  {
    id: 'legs-10',
    type: 'legs',
    title: 'Machine Leg Day',
    workout: [
      'Leg Press - 5 sets x 12 reps, RPE 7, rest 90s',
      'Leg Extension - 4 sets x 15 reps, RPE 7, rest 60s',
      'Leg Curl - 4 sets x 15 reps, RPE 7, rest 60s',
      'Standing Calf Raise - 4 sets x 15 reps, RPE 7, rest 60s',
      'Seated Calf Raise - 4 sets x 20 reps, RPE 7, rest 45s',
      'Hanging Leg Raise - 3 sets x 15 reps, RPE 7, rest 60s',
    ],
  },
]